name: Testing Angular Project
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Node 16.10
        uses: actions/setup-node@v1
        with:
          node-version: 16.10

      - name: Install depedencies
        run: |
          npm install
      - name: Testing Angular App
        run: |
          npm run test
