name: Testing Angular Project
on:
  push:
    branches:
     - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Install NodeJS v16.10
        uses: actions/setup-node@v1
        with:
          node-version: 16.10

      - name: Install depedencies
        run: |
          npm install
      - name: Building Angular App
        run: |
          npm run build
